
variables:
  NAME: zakupki-indexer
  REGISTRY: cr.yandex/crpo38oo32t6g3d5o5re

stages:
  - build
  - release
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test-and-build:
  image: adoptopenjdk:14-jdk-hotspot
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./gradlew
  script:
    - ./gradlew test
    - ./gradlew bootJar
  artifacts:
    expire_in: 1 hour
    paths:
      - indexer/build/libs/
      - zakupki-service/build/libs/

docker-build:
  image: docker
  stage: release
  cache: {}
  script:
    - docker build -t ${REGISTRY}/${NAME}:${CI_COMMIT_SHORT_SHA} .
    - docker tag ${REGISTRY}/${NAME}:${CI_COMMIT_SHORT_SHA} ${REGISTRY}/${NAME}:${CI_COMMIT_REF_SLUG}
    - docker push ${REGISTRY}/${NAME}:${CI_COMMIT_SHORT_SHA}
    - docker push ${REGISTRY}/${NAME}:${CI_COMMIT_REF_SLUG}
  only:
    - master
    - tags
    - metalog/KYC-42
    - Andrianov/KYC-43
    - Andrianov/KYC-45

argocd-deploy:
  image: ${REGISTRY}/argocd-cli:master
  stage: deploy
  cache: {}
  dependencies: []
  environment:
    name: staging
  variables:
    APP: staging-zakupki
  script:
    - argocd app set $APP --kustomize-image ${REGISTRY}/${NAME}:${CI_COMMIT_SHORT_SHA}
    - argocd app sync $APP --force || true
  only:
    - master
    - tags
    - metalog/KYC-42
    - Andrianov/KYC-43
    - Andrianov/KYC-45
